module: Health
author: IBM and the Kitura project authors
github_url: https://github.com/Kitura/Health/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, Health.xcodeproj, -target, Health, LIBRARY_SEARCH_PATHS=.build/debug]
