# docker-compose up
app:
  image: ibmcom/swift-ubuntu:4.0
  volumes:
    - .:/Health
  command: bash -c "cd /Health && swift package --build-path .build-ubuntu clean && swift build --build-path .build-ubuntu && swift test --build-path .build-ubuntu"
