# docker-compose up
app:
  image: ibmcom/swift-ubuntu:3.1.1
  volumes:
    - .:/root/Health
  command: bash -c "cd /root/Health && swift package clean && swift build && swift test && swift package clean"
